version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - JWT_SECRET_KEY=your-secret-key-here
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  api_ia:
    build:
      context: .
      dockerfile: Dockerfile.api_ia
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./src/api_ia/weights:/app/api_ia/weights
      - ./src/api_ia/models:/app/api_ia/models
    restart: unless-stopped

volumes:
  postgres_data: 