FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH=/app

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1-mesa-glx \
    curl \
    gnupg \
    libmagic1 \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    && rm -rf /var/lib/apt/lists/*

COPY src/api_ia/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

# Copier le code source de l'API IA
COPY --chown=appuser:appuser src/api_ia /app/api_ia

# Copier le dossier models pour les imports from models.*
COPY --chown=appuser:appuser src/models /app/models

# Exposer le port HTTP
EXPOSE 8000

CMD ["uvicorn", "api_ia.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
