global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api_ia'
    static_configs:
      - targets: ['api_ia:8000']
        labels:
          service: 'api_ia'
          environment: 'production'
